command:
- "python"
- "app.py"

env:
- name: "DATABRICKS_HOST"
  value: "adb-8928465560894847.7.azuredatabricks.net"  # Without https://
- name: "SERVING_ENDPOINT_NAME"
  valueFrom: "serving-endpoint"
- name: "GENIE_SPACE"
  valueFrom: "genie-space"
- name: "GUNICORN_TIMEOUT"
  value: "300"